[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.args]
NIXPKGS_CHANNEL = "nixpkgs-unstable"

# Variables de entorno necesarias para la aplicación
[build.environment]
PYTHON_VERSION = "3.10.13"

# Variables de entorno que el usuario debe configurar en Railway
[deploy.environment]
# Configuración de Flask
FLASK_APP = "app.py"
FLASK_ENV = "production"
SECRET_KEY = "milo-store-secret-key-2024"  # Cambia esto por una clave secreta segura

# Configuración de Google Sheets
GOOGLE_SHEETS_SHEET_ID = "1QG8a6yHmad5sFpVcKhC3l0oEAcjJftmHV2KAF56bkkM"
GOOGLE_SHEETS_SHEET_NAME = "Ingreso Diario"
GOOGLE_SHEETS_CATALOG_GID = "180421919"
GOOGLE_SHEETS_TIMEOUT = "10"
GOOGLE_SHEETS_RETRY_ATTEMPTS = "3"

# Configuración de la aplicación
HOST = "0.0.0.0"
PORT = "5000"

# Configuración de archivos
DATA_DIR = "data"
BACKUP_DIR = "backups"
USE_EXISTING_FILE = "True"
EXISTING_FILE_PATH = "Milo Store ERP.xlsx"

# Credenciales de Google Sheets (obligatorio configurar)
# Reemplaza con tus credenciales en formato JSON de Google Cloud
# GOOGLE_SHEETS_CREDENTIALS = '{"type": "service_account", ...}'
